### ISSUE TITLE
'sample_1_R1.fq' has size 0. Returning a NULL data.frame.  Execution halted

### ISSUE THREAD

**Issue by AlexMerkelBio** [MelcyPhilip/METASEED#10]
Got this error when performing an analysis on your test data

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): readpair_id, read_id, seed_id
dbl (2): n_hits, abundance

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in seq.default(1, nrow(tbl), 4) : wrong sign in 'by' argument
Calls: %>% ... <Anonymous> -> [ -> [.data.frame -> seq -> seq.default
In addition: Warning message:
File '/media/alex/BigDisk/tools/METASEED/tmp/sample_1_R1.fq' has size 0. Returning a NULL data.frame. 
Execution halted

**Comment by MelcyPhilip** [comment]
Hi Alex, 

I did a trial run on the sample data and it works fine. Can you make sure that there was no errors while downloading or extracting the file from the tar file? The whole tar file is ~4.0GB+.  Each sample files should be nearly 956 MB. Additionally, make sure you have right path to folders, and all the containers. From the error I asssume the errors are in the first steps where the alignments are done. It would be helful to see the whole log file..

Good luck!

**Comment by AlexMerkelBio** [comment]
Dear Melcy,

I think I realized why such an error appeared - you need to clear the METASEED/tmp folder before launching METASEED_main.sh.

**Comment by MelcyPhilip** [comment]
Hi again, 

That is great, I had empty folders before I started the analysis.
