### ISSUE TITLE
Data link on README.md might be wrong

### ISSUE THREAD

**Issue by naturepoker** [MelcyPhilip/METASEED#8]
Hello, 

The demonstration data link embedded on the readme page might be wrong - it looks like the '/share/' path portion could be missing. 

https://arken.nmbu.no/~pmelcy/share/METASEED/METASEED.tar.gz

Thank you for sharing your work, and looking forward to trying out your pipeline!

**Comment by MelcyPhilip** [comment]
Thank you for the comments; it has been updated now.
